language: generic
branches:
  only:
  - master
  - "/^v.*$/"
matrix:
  include:
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew upgrade python@2
    - pip2 install virtualenv
    - python2 -m virtualenv env
    - source env/bin/activate
  - os: osx
    language: generic
    before_install:
    - brew update
    - python3 -m venv env
    - source env/bin/activate
  - services: docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    install: bash .manylinux.sh
    script: true
  - services: docker
    env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    - PRE_CMD=linux32
    install: bash .manylinux.sh
    script: true
install:
- pip install --upgrade pip wheel
- pip install .[test]
- python setup.py bdist_wheel
script:
- python setup.py test
deploy:
  provider: releases
  api_key:
    secure: oYq+Hct0XzGfTg51AhubX9gwqUmQt+vP8z2Ba+IVNliTScmyUbHqDqCYbefW5+6iKDMIsbuxMaHTGlXgDhZZy0Tro/1tLRsq198poNmHd5yCoqelwXwDGu/SviJl7JCRIxW1MDmyrKBuX5MkmXRQ8SHVGIppkaO15aMI7gjhi0tjRduBrnrVvPlaqPHMqNq1TxWy+X4265UzZ4xbfkHyMgbsHkepqhaJp6NkJiB/M0kVuYeLRAhXJSemde+Z8VQsHO8Y/AQ6jujUtjdPceDfAvieg62lQH29FGF1msUkzg5gAYoj36rAhDIl6mmdKGr5SsYAvZGuwc6My1sWuJ18p9fJR8S83y++A0RLcurLyrkf3qvuuz3wPpzshn6OgDQn3f6SXqqALxC9BPOrH/fkBkM5VyyEkcbbT8ySpJX4qZj1+5Mqn5RLERYl5C6surTPyv0VssmPrqwo1Vu0Xk1wbI5gmbOB1NmgrJizms1KxIcjp51MdBdjyCEZXw1fkGXA/kei3GxGYEY0svnWywXkwy9tgh4m+W07db5IgYKXs8jXV4R/4VIsTWXyOF0UYTs8Ld6qp7FUdfYLIId4CRVLkxUQZweadEwRLj5EWSs22vlXHGlqc2uk5ZnrHEN5ZHSGHxxiLPAozJHIzXJOv7KB6FJlCDMsmCNcSWDKg6hM7SU=
  file_glob: true
  file: dist/fastcluster*.whl
  skip_cleanup: true
  on:
    repo: dmuellner/fastcluster
    tags: true
