language: generic
branches:
  only:
  - master
  - /^v.*$/
matrix:
  include:
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew upgrade python
      - brew install python2
      - pip install virtualenv
      - python2 -m virtualenv env
      - source env/bin/activate
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew versions python
      - brew install python
      - python3 -m venv env
      - source env/bin/activate
  - services: docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    install: bash .manylinux.sh
    script: true
  - services: docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
      - PRE_CMD=linux32
    install: bash .manylinux.sh
    script: true
install:
- pip install --upgrade pip wheel
- pip install .[test]
- python setup.py bdist_wheel
script:
- python setup.py test
deploy:
  provider: releases
  api_key:
    secure: Spde4nnDLwoQvazn9VUyjCDzFQPoSL69eZCyZdCa6PBlFI/RKiu4K/xH/jQZrHMh+1YUV6VMMZCFAZJIcbv7Outqeh6uVER1pyFYn7LLXKzANI87PV/I38HVQ8g+SKP5YyBUKRVnrNl9lPtSaMl8caL3x+ht/dVDyI0ZwujgRreL9qXf5V7s0H/P2IQQsPyFAV3kilYckT7xDnQdJ1KxRc820PQqHid6/04Lz/NUuwUBMQ88AeEaiHLK7/O4k9X/AQr0yozBTafBpyqqZ/rg/Carh4TpglSdovyIYF431Sa9hLi0ge2UjU2vNPnhsDRzaUjOzeqR2OmyDz9NE/0SZPWWrvlqR2GDWeIx/lYR3Qw8wWlNPzZpImxi0YOOcS098M6wdzphISrJVtTCs9EwwWqoT/STDIZ8cS3TnCq4p74k7QasGsL+Qp8gdgs4PnVdCbFSGZRSySSofhYO6QhuCoiM246OLg+RBy3z/XGQT+vsWQG8aCoX9tyJ5651rdtazRCQQUzrv8JyMZqiAmZ/BkFuFqUL0+nQkU49ykXlSP/RxaJEaReaJ72qMXe9RsT096pQkOX7sZ6qQtENVlaufd3jhZarD9PvhGGvFn/Bzrre2ROiBbUYY+G+d0Qg0YZd7wwbqlcB713pFr3yJ/9fxMlc6MkDhPqzRTQI+4/6bqY=
  file_glob: true
  file: dist/fastcluster*.whl
  skip_cleanup: true
  on:
    repo: dmuellner/fastcluster
    tags: true
