language: generic
branches:
  only:
  - master
  - "/^v.*$/"
jobs:
  include:
  - os: osx
    # TODO: Update according to https://docs.travis-ci.com/user/reference/osx/#macos-version.
    osx_image: xcode12.5
    language: generic
    before_install:
    - python3 -m venv env
    - source env/bin/activate
  - services: docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    install: bash .manylinux.sh
    script: true
  - services: docker
    env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    - PRE_CMD=linux32
    install: bash .manylinux.sh
    script: true
install:
- pip install --upgrade pip wheel
- pip install .[test]
- python setup.py bdist_wheel
script:
- python setup.py test
deploy:
  provider: releases
  token:
    secure: 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
  file_glob: true
  file: dist/fastcluster*.whl
  skip_cleanup: true
  on:
    repo: dmuellner/fastcluster
    tags: true
